version: '3.8'

services:
  backend:
    build: ./backend
    container_name: medichain-backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: medichain-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
